Vagrant.configure("2") do |config|
    # 设置虚拟机的Box
    config.vm.box = "ubuntu/focal64"
    config.vm.box_url = "https://mirrors.ustc.edu.cn/ubuntu-cloud-images/focal/current/focal-server-cloudimg-amd64-vagrant.box"
    #config.disksize.size = "50GB"
	(1..5).each do |i|
		config.vm.define "node#{i}" do |node|
            # 设置虚拟机的主机名
            node.vm.hostname="node#{i}"
            # 设置虚拟机的IP
            node.vm.network "private_network", ip: "192.168.60.2#{i}"
            # 设置主机与虚拟机的共享目录
            node.vm.synced_folder "~/Desktop", "/home/vagrant/share"
            # VirtaulBox相关配置
            node.vm.provider "virtualbox" do |v|
                # 设置虚拟机的名称
                v.name = "node#{i}"
                # 设置虚拟机的内存大小
                v.memory = 6144
                # 设置虚拟机的CPU个数
                v.cpus = 2
            end
            # 使用shell脚本进行软件安装和配置
            node.vm.provision "shell", path: "start.sh", args: i
		end
	end
end
