Vagrant.configure("2") do |config|
	(0..6).each do |i|
		config.vm.define "node#{i}" do |node|
		# 设置虚拟机的Box
		node.vm.box = "ubuntu/focal64"
		config.vm.box_url = "https://mirrors.ustc.edu.cn/ubuntu-cloud-images/focal/current/focal-server-cloudimg-amd64-vagrant.box"
		# 设置虚拟机的主机名
		node.vm.hostname="node#{i}"
		# 设置虚拟机的IP
		node.vm.network "private_network", ip: "172.20.0.2#{i}"
		# 设置主机与虚拟机的共享目录
		node.vm.synced_folder "~/Desktop/share", "/home/vagrant/share"
		# VirtaulBox相关配置
		node.vm.provider "virtualbox" do |v|
			# 设置虚拟机的名称
			v.name = "node#{i}"
			# 设置虚拟机的内存大小  
			v.memory = 4096
			# 设置虚拟机的CPU个数
			v.cpus = 2
		end
		# 使用shell脚本进行软件安装和配置
		node.vm.provision "shell", inline: <<-SHELL
sudo echo root:45678o@test | chpasswd
sudo sed -i '/PermitRootLogin prohibit-password/d' /etc/ssh/sshd_config
sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sudo echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
sudo systemctl restart sshd
sudo echo 'apt_preserve_sources_list: true' >> /etc/cloud/cloud.cfg
sudo echo 'deb http://mirrors.aliyun.com/ubuntu/ focal main restricted' > /etc/apt/sources.list
sudo echo 'deb http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted' >> /etc/apt/sources.list
sudo echo 'deb http://mirrors.aliyun.com/ubuntu/ focal universe' >> /etc/apt/sources.list
sudo echo 'deb http://mirrors.aliyun.com/ubuntu/ focal-updates universe' >> /etc/apt/sources.list
sudo echo 'deb http://mirrors.aliyun.com/ubuntu/ focal multiverse' >> /etc/apt/sources.list
sudo echo 'deb http://mirrors.aliyun.com/ubuntu/ focal-updates multiverse' >> /etc/apt/sources.list
sudo echo 'deb http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse' >> /etc/apt/sources.list
sudo echo 'deb http://mirrors.aliyun.com/ubuntu/ focal-security main restricted' >> /etc/apt/sources.list
sudo echo 'deb http://mirrors.aliyun.com/ubuntu/ focal-security universe' >> /etc/apt/sources.list
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install -y chrony
sudo systemctl start chrony
		SHELL
		end
	end
end
